global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "churn-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["churn-api:8000"]
        labels:
          service: "churn-prediction-api"
          environment: "local"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
